# Global defaults
global:
  T: 200 # should be the same as input_length and output_length in the prediction section of each experiment
  n_seeds: 1
  seed_offset: 0

experiments:
  # -----------------------
  # Experiment 1: RW drift
  # -----------------------
  - id: 1
    name: "RW drift"
    generator:
      type: "rw_drift"
      params:
        x0: 0.0
        sigma: 1.0
      sweep:
        mu: [-0.04, -0.02, 0.02, 0.04]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "prob_positive"

  # -----------------------
  # Experiment 2: AR(1) persistence
  # -----------------------
  - id: 2
    name: "AR(1) persistence"
    generator:
      type: "ar1"
      params:
        x0: 0.0
        c: 0.0
        sigma: 1.0
      sweep:
        phi: [0.2, 0.5, 0.8, 0.95]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "beta_hat"

  # -----------------------
  # Experiment 3: HO wavelength
  # -----------------------
  - id: 3
    name: "HO wavelength"
    generator:
      type: "harmonic"
      params:
        A: 1.0
        phase: 0.0
        offset: 0.0
        sigma: 0.05
      sweep:
        wavelength: [5, 10, 20, 50]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "dominant_frequency"

  # -----------------------
  # Experiment 4: AR(1) noise
  # -----------------------
  - id: 4
    name: "AR(1) noise"
    generator:
      type: "ar1"
      params:
        x0: 0.0
        c: 0.0
        phi: 0.5
      sweep:
        sigma: [0.1, 0.3, 1.0, 3.0]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "beta_hat"

  # -----------------------
  # Experiment 5: HO amplitude
  # -----------------------
  - id: 5
    name: "HO amplitude"
    generator:
      type: "harmonic"
      params:
        wavelength: 10
        phase: 0.0
        offset: 0.0
        sigma: 0.05
      sweep:
        A: [0.25, 0.5, 1.0, 2.0]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "dominant_frequency"

  # -----------------------
  # Experiment 6: Regime Switch
  # -----------------------
  - id: 6
    name: "RS dwell time"
    generator:
      type: "regime"
      params:
        slopes: [1.0, -1.0]
        sigma: 0.05
      sweep:
        dwell_time: [5, 10, 20, 50]
    prediction:
      input_length: 200
      output_length: 200
    analysis:
      param_stat: "estimated_dwell_time"