import numpy as np

class PayoffAllocationGame:
    """
    Simulates a payoff allocation game where a portfolio is managed by an observer
    based on values generated by a generator over a series of time steps.

    Attributes:
        generator (object): Generates new values at each time step.
        observer (object): Decides portfolio allocations based on observed values.
        T (int): Total number of time steps in the game.
        initial_portfolio (float): Starting value of the portfolio.
        portfolio (float): Current portfolio value.
        previous_values (dict): Values generated in the previous time step.
        portfolio_development (numpy.ndarray): Tracks portfolio values over time.
        allocation_development (numpy.ndarray): Tracks portfolio allocations over time.
    """

    def __init__(self, generator, observer, T, initial_values, initial_portfolio=100):
        """
        Initializes the game with a generator, observer, and key parameters.

        Args:
            generator (object): Generates new values for the game.
            observer (object): Allocates the portfolio based on observations.
            T (int): Total number of time steps.
            initial_values (dict): Initial values for the generator.
            initial_portfolio (float, optional): Starting portfolio value. Default is 100.
        """
        self.generator = generator
        self.observer = observer
        self.T = T
        self.initial_portfolio = initial_portfolio
        self.portfolio = initial_portfolio
        self.previous_values = initial_values
        self.portfolio_development = np.array([])
        self.allocation = np.array([])
        self.allocation_development = np.array([])

    def play_turn(self):
        """
        Performs a single time step in the game.

        - Generates new values from the generator.
        - Obtains portfolio allocation from the observer.
        - Computes returns and updates the portfolio value.
        - Records portfolio and allocation changes.
        """
        # Generate new values for the current time step
        self.values = self.generator.generate()

        # Obtain portfolio allocation from the observer
        allocation = self.observer.make_allocation()

        # Calculate returns based on changes in values
        self.returns = (self.values - self.previous_values) / self.previous_values

        # Compute the weighted average return, excluding cash allocation
        weighted_avg_return = np.dot(allocation[1:], self.returns)

        # Update portfolio value
        self.portfolio *= (1 + weighted_avg_return)

        # Record portfolio and allocation changes
        self.portfolio_development = np.append(self.portfolio_development, self.portfolio)
        self.allocation_development = np.append(self.allocation_development, allocation)

        # Update previous values for the next time step
        self.previous_values = self.values

    def observe(self):
        """
        Allows the observer to update its strategy based on the current values and returns.
        """
        self.observer.observe(self.values, self.returns)

    def play_game(self):
        """
        Executes the game over all time steps.

        Returns:
            float: Final portfolio value after all time steps.
        """
        for _ in range(self.T):
            self.observe()  # Update observer with the current state
            self.play_turn()  # Perform a single game turn

        return self.portfolio

# Example usage
# Uncomment and replace with actual implementations of generator and observer classes to test.
# generator = GeneratorClass()
# observer = ObserverClass()
# initial_values = {"value1": 100, "value2": 200}
# game = PayoffAllocationGame(generator, observer, T=50, initial_values=initial_values)
# final_portfolio = game.play_game()
# print(f"Final portfolio value: {final_portfolio}")
